version: "3"
services:
  frontend:
    build: "./frontend"
    ports:
      - "3000:3000"

  submitproblem:
    build: "./submitproblem"
    ports:
      - "5000:5000"
    depends_on:
      - db
      - rabbitmqquestions
    environment:
      - MONGO_DB_URI=mongodb://db/microservices1
      - RABBITMQ_QUESTIONS_URL=amqp://guest:guest@rabbitmqquestions:5672/
      - EXCHANGE_NAME=questionsExchange
      - JWT_KEY="arandomjwtkey"

  usersmanagement:
    build: "./usersmanagement"
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/users
      - JWT_KEY="arandomjwtkey"

  showsubmissions:
    build: "./showsubmissions"
    ports:
      - "5002:5000"
    depends_on:
      - db
      - rabbitmqquestions
    environment:
      - MONGO_DB_URI=mongodb://db/microservices2
      - RABBITMQ_QUESTIONS_URL=amqp://guest:guest@rabbitmqquestions:5672/
      - EXCHANGE_NAME=questionsExchange
      - QUEUE_SHOW_SUBMISSIONS=showSubmissionsQueue
      - QUEUE_VIEW_RESULTS=viewResultsQueue
      - JWT_KEY="arandomjwtkey"

  db:
    image: mongo
    ports:
      - "27016:27017"

  rabbitmqquestions:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672

  # rabbitmqanswers:
  #   image: rabbitmq:3-management
  #   ports:
  #     - 5673:5672
  #     - 15673:15672
  #     - 25673:25672

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - submitproblem
      - usersmanagement
      - showsubmissions
