version: '3'
services:
  submitproblem:
    build: './submitproblem'
    ports:
      - "5000:5000"

  showsubmissions:
    build: './showsubmissions'
    ports:
      - "5001:5000"


  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - submitproblem
      - showsubmissions
